# ------------------------------- configuration for Event -------------------------------------#
particle_types:
  digis:
    amount: 'digi_nDigis'
    branches:
      wh: 'digi_wheel'
      sc: 'digi_sector'
      st: 'digi_station'
      sl: 'digi_superLayer'
      w: 'digi_wire'
      l: 'digi_layer'
      time: 'digi_time'
    attributes:
      BX:
        expr: 'int(time // 25) if time is not None else None'
    sorter:
      by: 'p.BX'
  emushowers:
    amount: 'ph2Shower_station'
    branches:
      wh: 'ph2Shower_wheel'
      sc : 'ph2Shower_sector'
      st: 'ph2Shower_station'
      sl: 'ph2Shower_superlayer'
      nDigis: 'ph2Shower_ndigis'
      BX: 'ph2Shower_BX'
      min_wire: 'ph2Shower_min_wire'
      max_wire: 'ph2Shower_max_wire'
      avg_pos: 'ph2Shower_avg_pos'
      avg_time: 'ph2Shower_avg_time'
      wires_profile: 'ph2Shower_wires_profile'

# -------------------------------- configuration for NTuple --------------------------------------#
ntuple_tree_name: '/dtNtupleProducer/DTTREE'
